<?xml version="1.0"?>
<!--

  Copyright (c) 2011-2014, PAL Robotics, S.L.
  All rights reserved.

  This work is licensed under the Creative Commons Attribution-NonCommercial-NoDerivs 3.0 Unported License.
  To view a copy of this license, visit http://creativecommons.org/licenses/by-nc-nd/3.0/ or send a letter to
  Creative Commons, 444 Castro Street, Suite 900, Mountain View, California, 94041, USA.
-->
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ant_description)/urdf/deg_to_rad.xacro"/>

  <xacro:include filename="$(find ant_description)/urdf/wheels/wheel_v2.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/wheels/caster_v2.urdf.xacro"/>

  <xacro:include filename="$(find ant_description)/urdf/sensors/range.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/sensors/sick_tim551_laser.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/sensors/xtion_pro_live.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/sensors/imu.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/sensors/bumper.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/sensors/ir_receiver.urdf.xacro"/>
  <xacro:include filename="$(find ant_description)/urdf/antennas/antenna_array.urdf.xacro"/>

  <!-- Wheel characteristics -->
  <property name="wheel_radius"     value="0.0985"/>
  <property name="wheel_width"      value="0.040"/>
  <property name="wheel_separation" value="0.4226"/>
  <property name="wheel_torque"     value="6.0"/>
  <property name="wheel_velocity"   value="1.0"/>

  <!-- Caster wheel characteristics -->
  <property name="caster_radius"       value="0.025"/>
  <property name="caster_width"        value="0.015"/>
  <property name="caster_separation_x" value="0.36384"/>
  <property name="caster_separation_y" value="0.20168"/>
  <property name="caster_offset_z"     value="-0.0335"/>

  <!-- Laser characteristics -->
  <property name="base_laser_x" value="0.185"/> <!-- measured value it's approx. 0.1593 -->
  <property name="base_laser_y" value="0.0"/>
  <property name="base_laser_z" value="0.0498"/>

  <!-- base RGBD characteristics -->
  <property name="base_rgbd_x" value="0.1"/>
  <property name="base_rgbd_y" value="0.0"/>
  <property name="base_rgbd_z" value="0.61"/>
  <property name="base_rgbd_R" value="0.19"/>
  <property name="base_rgbd_P" value="21.85"/>
  <property name="base_rgbd_Y" value="-0.15"/>

  <!-- roof RGBD characteristics -->
  <property name="roof_rgbd_x" value="0.1"/>
  <property name="roof_rgbd_y" value="0.0"/>
  <property name="roof_rgbd_z" value="0.652"/>
  <property name="roof_rgbd_R" value="-0.08"/>
  <property name="roof_rgbd_P" value="-24.07"/>
  <property name="roof_rgbd_Y" value="0.2"/>

  <!-- Antennas characteristics -->
  <!-- @todo ${wheel_separation + wheel_width} fails -->
  <property name="antenna_separation_y" value="0.2"/>
  <property name="antenna_height_0"     value="0.4"/>
  <property name="antenna_height_inc"   value="0.40"/>

  <xacro:macro name="base" params="name">

    <!-- Base -->
    <link name="${name}_link">
      <inertial>
        <origin xyz="0.00144 0.00003 0.06711" rpy="0 0 0" />
        <mass value="24.73813" />
        <inertia ixx="0.50215676906" ixy="0.00014630224" ixz="-0.00851406322"
                 iyy="0.41873574615" iyz="0.00001868612"
                 izz="0.64067017495" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://ant_description/meshes/base/base_v2.stl" />
        </geometry>
        <material name="DarkGrey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://ant_description/meshes/base/base_v2_collision.stl" />
        </geometry>
        <material name="DarkGrey" />
      </collision>
    </link>

    <!-- Base footprint -->
    <link name="${name}_footprint"/>

    <joint name="${name}_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
      <child link="${name}_link" />
      <parent link="${name}_footprint"/>
    </joint>

    <!-- Laser -->
    <!-- Theoretic FOV = 220deg -->
    <xacro:sick_tim551_laser name="${name}_laser" parent="${name}" ros_topic="scan" update_rate="15" min_angle="${-110 * deg_to_rad}" max_angle="${110 * deg_to_rad}" >
      <origin xyz="${base_laser_x} ${base_laser_y} ${base_laser_z}" rpy="0 0 0" />
    </xacro:sick_tim551_laser>

    <!-- RGBD -->
    <xacro:xtion_pro_live name="base_rgbd_camera" parent="${name}">
      <!-- Pose of sensor frame wrt to base -->
      <origin xyz="${base_rgbd_x} ${base_rgbd_y} ${base_rgbd_z}" rpy="${base_rgbd_R * deg_to_rad} ${base_rgbd_P * deg_to_rad} ${base_rgbd_Y * deg_to_rad}"/>
      <!-- Pose of optical frame wrt to sensor -->
      <origin xyz="0 0 0" rpy="${-90 * deg_to_rad} 0 ${-90 * deg_to_rad}"/>
    </xacro:xtion_pro_live>

    <!-- RGBD "roof" -->
    <xacro:xtion_pro_live name="roof_rgbd_camera" parent="${name}">
      <!-- Pose of sensor frame wrt to base -->
      <origin xyz="${roof_rgbd_x} ${roof_rgbd_y} ${roof_rgbd_z}" rpy="${roof_rgbd_R * deg_to_rad} ${roof_rgbd_P * deg_to_rad} ${roof_rgbd_Y * deg_to_rad}"/>
      <!-- Pose of optical frame wrt to sensor -->
      <origin xyz="0 0 0" rpy="${-90 * deg_to_rad} 0 ${-90 * deg_to_rad}"/>
    </xacro:xtion_pro_live>

    <!-- Sonar -->
    <!--xacro:range_sensor name="${name}_sonar_02" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="0.18 0.0 0.04" rpy="0.0 ${-10.0 * deg_to_rad} 0.0" />
    </xacro:range_sensor-->

    <!-- Sonar -->
    <!--xacro:range_sensor name="${name}_sonar_03" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="0.15 0.1 0.04" rpy="0.0 ${-10.0 * deg_to_rad} ${40.0 * deg_to_rad}" />
    </xacro:range_sensor-->

    <!-- Sonar -->
    <!--xacro:range_sensor name="${name}_sonar_01" parent="${name}" ros_topic="sonar_base" update_rate="10" maxRange="0.75" minRange="0.01" fov="0.5" radiation="ultrasound">
      <origin xyz="0.15 -0.1 0.04" rpy="0.0 ${-10.0 * deg_to_rad} ${-40.0 * deg_to_rad}" />
    </xacro:range_sensor-->

    <!-- Bumper right -->
    <!--xacro:bumper name="${name}_bumper_01" parent="${name}" ros_topic="bumper_base" update_rate="25" >
      <origin xyz="0.16 -0.12 0.00" rpy="0 0 ${-20.0 * deg_to_rad}" />
    </xacro:bumper-->

    <!-- Bumper left -->
    <!--xacro:bumper name="${name}_bumper_02" parent="${name}" ros_topic="bumper_base" update_rate="25" >
      <origin xyz="0.16 0.12 0.00" rpy="0 0 ${20.0 * deg_to_rad}" />
    </xacro:bumper-->

    <!-- IMU -->
    <!-- @todo ant_hardware_gazebo needs an IMU!  -->
    <xacro:imu_sensor name="base_inclinometer" parent="${name}_link" update_rate="100.0">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:imu_sensor>

    <!-- IR receiver -->
    <!--xacro:ir_receiver name="${name}_ir_receiver_01" parent="${name}" ros_topic="ir_receiver_base" update_rate="10" range_min="0.0" range_max="0.75" fov="0.5">
      <origin xyz="0.17131 0.0 0.180" rpy="0.0 0.0 0.0" />
    </xacro:ir_receiver-->

    <!-- IR receiver -->
    <!--xacro:ir_receiver name="${name}_ir_receiver_02" parent="${name}" ros_topic="ir_receiver_base" update_rate="10" range_min="0.0" range_max="0.75" fov="0.5">
      <origin xyz="0.16919 0.14919 0.180" rpy="0.0 0.0 0.349" />
    </xacro:ir_receiver-->

    <!-- IR receiver -->
    <!--xacro:ir_receiver name="${name}_ir_receiver_03" parent="${name}" ros_topic="ir_receiver_base" update_rate="10" range_min="0.0" range_max="0.75" fov="0.5">
      <origin xyz="0.16919 -0.14919 0.180" rpy="0.0 0.0 -0.349" />
    </xacro:ir_receiver-->

    <!-- Wheels -->
    <xacro:wheel side="right" reflect=" 1.0" radius="${wheel_radius}" width="${wheel_width}" torque="${wheel_torque}" velocity="${wheel_velocity}" separation="${wheel_separation}" parent="${name}"/>
    <xacro:wheel side="left"  reflect="-1.0" radius="${wheel_radius}" width="${wheel_width}" torque="${wheel_torque}" velocity="${wheel_velocity}" separation="${wheel_separation}" parent="${name}"/>

    <!-- Casters wheels -->
    <xacro:caster side="front_right" radius="${caster_radius}" width="${caster_width}" separation_x="${ caster_separation_x}" separation_y="${ caster_separation_y}" offset_z="${caster_offset_z}" parent="${name}"/>
    <xacro:caster side="front_left"  radius="${caster_radius}" width="${caster_width}" separation_x="${ caster_separation_x}" separation_y="${-caster_separation_y}" offset_z="${caster_offset_z}" parent="${name}"/>

    <xacro:caster side="back_right"  radius="${caster_radius}" width="${caster_width}" separation_x="${-caster_separation_x}" separation_y="${ caster_separation_y}" offset_z="${caster_offset_z}" parent="${name}"/>
    <xacro:caster side="back_left"   radius="${caster_radius}" width="${caster_width}" separation_x="${-caster_separation_x}" separation_y="${-caster_separation_y}" offset_z="${caster_offset_z}" parent="${name}"/>

    <!-- Antennas -->
    <xacro:antenna_array_4 name="antenna" parent="base_link" side="left"  reflect=" 1.0" separation_y="${antenna_separation_y}" height_0="${antenna_height_0}" height_inc="${antenna_height_inc}" />
    <xacro:antenna_array_4 name="antenna" parent="base_link" side="right" reflect="-1.0" separation_y="${antenna_separation_y}" height_0="${antenna_height_0}" height_inc="${antenna_height_inc}" />

  </xacro:macro>

</robot>
