play_motion:
  controllers: [arm_controller, head_controller, torso_controller, hand_controller]
  motions:
    home:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.15, 0.21, 0.35, 0.0, 0.0, -1.57, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.15, 0.21, 0.35, -0.2, 0.0, -1.57, 1.52, 0.0]
        time_from_start: 1.5
      - positions: [0.15, 0.21, 0.35, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 3.5
      - positions: [0.15, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 6.0
      - positions: [0.09, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 9.0
      meta:
        name: Home
        usage: demo
        description: 'Go home'

    pregrasp:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.09, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 0.0
      - positions: [0.34, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 1.5
      - positions: [0.34, 0.21, 0.35, -0.2, 2.12, -1.57, 1.52, 0.0]
        time_from_start: 4.5
      - positions: [0.34, 0.21, 0.35, -0.2, 0.0, -1.57, 1.52, 0.0]
        time_from_start: 8.0
      - positions: [0.34, 0.21, 0.35, -3.0, 0.0, -1.57, 1.52, 0.0]
        time_from_start: 10.0
      - positions: [0.34, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
        time_from_start: 12.0
      meta:
        name: pregrasp
        usage: demo
        description: 'pregrasp'

    open_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, -1.0, -1.0]
        time_from_start: 0.1
      - positions: [0.0, 0.0, 0.0]
        time_from_start: 1.5
      meta:
        name: open_hand
        usage: demo
        description: 'open_hand'

    close_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [2.37, 0.0, 0.0]
        time_from_start: 0.1
      - positions: [6.2, 6.8, 9.2]
        time_from_start: 1.5
      meta:
        name: close_hand
        usage: demo
        description: 'close_hand'

    pointing_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [2.37, -1.0, 0.0]
        time_from_start: 0.1
      - positions: [6.2, 0.0, 9.2]
        time_from_start: 1.5
      meta:
        name: pointing_hand
        usage: demo
        description: 'pointing_hand'

    gun_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, -1.0, 0.0]
        time_from_start: 0.1
      - positions: [0.0, 0.0, 9.2]
        time_from_start: 1.5
      meta:
        name: gun_hand
        usage: demo
        description: 'gun_hand'

    thumb_up_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [-1.0, 0.0, 0.0]
        time_from_start: 0.1
      - positions: [0.0, 6.8, 9.2]
        time_from_start: 1.5
      meta:
        name: thumb_up_hand
        usage: demo
        description: 'thumb_up_hand'

    pregrasp_thumb_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [0.0, -1.0, -1.0]
        time_from_start: 0.1
      - positions: [3.37, 0.0, 0.0]
        time_from_start: 1.5
      meta:
        name: pregrasp_thumb_hand
        usage: demo
        description: 'pregrasp_thumb_hand'

    pinch_hand:
      joints: [hand_thumb_joint, hand_index_joint, hand_mrl_joint]
      points:
      - positions: [0.0, -1.0, -1.0]
        time_from_start: 0.1
      - positions: [3.37, 4.0, 0.0]
        time_from_start: 1.5
      meta:
        name: pinch_hand
        usage: demo
        description: 'pinch_hand'

    head_tour:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0, 0]
        time_from_start: 0.1
      - positions: [0.7, 0]
        time_from_start: 3.0
      - positions: [0.7, 0.3]
        time_from_start: 6.0
      - positions: [0.7, -0.3]
        time_from_start: 9.0
      - positions: [0.7, 0.3]
        time_from_start: 12.0
      - positions: [-0.7, 0.3]
        time_from_start: 15.0
      - positions: [-0.7, -0.3]
        time_from_start: 18.0
      - positions: [0, 0]
        time_from_start: 21.0
      meta:
        name: head_tour
        usage: demo
        description: 'head_tour'

    wave:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint,
      arm_5_joint, arm_6_joint, arm_7_joint,
      hand_thumb_joint, hand_mrl_joint, hand_index_joint]
      points:
      - positions: [0.35, 0.06337464909724033, -0.679638896132783, -3.1087325315620733, 2.0882339360702575, -1.1201172410014792, -0.031008601325809293, -2.0744261217334135, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.35, 0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135, 0.0, 0.0, 0.0]
        time_from_start: 1.0
      - positions: [0.35, 0.06335930908588873, -0.7231278283145929, -2.9385504456273295, 2.2121050027803877, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135, 0.0, 0.0, 0.0]
        time_from_start: 2.0
      - positions: [0.35, 0.06335930908588873, -0.7354151774072313, -2.939624246421942, 1.8341256735249563, -1.1201355028397157, -0.031008601325809293, -2.0744261217334135, 0.0, 0.0, 0.0]
        time_from_start: 3.0
      meta:
        name: Wave
        usage: demo
        description: 'wave'

    pregrasp_weight:
      joints: [torso_lift_joint, arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [0.10, 1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      meta:
        name: pregrasp_weight
        usage: demo
        description: 'Pregrasp weight'

    do_weights:
      joints: [arm_1_joint,
      arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
      arm_6_joint, arm_7_joint]
      points:
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 1.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 2.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 4.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 6.0
      - positions: [1.6, -0.90, -3.16, 2.0, -1.57, 0.35, 0.0]
        time_from_start: 8.0
      - positions: [1.6, -1.57, -3.16, 1.62, -1.57, -0.2, 0.0]
        time_from_start: 10.0
      - positions: [1.6, -1.18, -3.16, 2.0, -1.57, -0.07, 0.0]
        time_from_start: 12.0
      meta:
        name: do_weights
        usage: demo
        description: 'Do weights'

    # pick_from_floor:
    #   joints: [torso_lift_joint, head_1_joint, head_2_joint, arm_1_joint,
    #   arm_2_joint, arm_3_joint, arm_4_joint,
    #   arm_5_joint, arm_6_joint, arm_7_joint,
    #   hand_thumb_joint, hand_mrl_joint, hand_index_joint]
    #   points:
    #   - positions: [0.06, -0.03, -0.66, 1.34, -1.08, 0.14, -0.55, -1.46, -0.71, 0.041, 0.0, 0.0, 0.0]
    #     time_from_start: 0.0
    #   - positions: [0.06, -0.03, -0.66, 1.34, -1.3, 0.14, -0.55, -1.46, -0.71, 0.041, 0.0, 0.0, 0.0]
    #     time_from_start: 2.0
    #   - positions: [0.06, -0.03, -0.66, 1.34, -1.3, 0.14, -0.20, -1.46, -0.80, 0.041, 0.0, 0.0, 0.0]
    #     time_from_start: 4.0
    #   - positions: [0.06, -0.03, -0.66, 1.34, -1.3, 0.14, -0.20, -1.46, -0.80, 0.041, 6.2, 6.8, 9.2]
    #     time_from_start: 8.0
    #   - positions: [0.06, 0.0, 0.4, 1.34, -0.39, 0.14, -1.57, -1.46, -0.71, 0.041, 6.2, 6.8, 9.2]
    #     time_from_start: 10.0
    #   meta:
    #     name: pick_from_floor
    #     usage: demo
    #     description: 'pick_from_floor'


    #############################################################################
    ### Motions demo video: grasping Luke Skywalker from a table 0.7 m tall #####
    #############################################################################
    look_forward:
      joints: [head_1_joint, head_2_joint]
      points:
      - positions: [0.0, 0.0]
        time_from_start: 2.0
      meta:
        name: look_forward
        usage: demo
        description: 'look_forward'

    # look_to_object_grasp1:
    #   joints: [head_1_joint, head_2_joint]
    #   points:
    #   - positions: [-0.05, -0.63]
    #     time_from_start: 2.0
    #   meta:
    #     name: look_to_object_grasp1
    #     usage: demo
    #     description: 'look_to_object_grasp1'

    # look_to_hand_before_grasp1:
    #   joints: [head_1_joint, head_2_joint]
    #   points:
    #   - positions: [-0.88, 0.07]
    #     time_from_start: 2.0
    #   meta:
    #     name: look_to_hand_before_grasp1
    #     usage: demo
    #     description: 'look_to_hand_before_grasp1'

    # pregrasp1:
    #   joints: [torso_lift_joint, head_1_joint, head_2_joint, arm_1_joint,
    #   arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
    #   arm_6_joint, arm_7_joint]
    #   points:
    #   - positions: [0.06, 0.0, 0.0, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
    #     time_from_start: 0.0
    #   - positions: [0.34, 0.0, 0.0, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0]
    #     time_from_start: 1.5
    #   - positions: [0.34, 0.0, 0.0, 0.21, 0.35, -0.2, 2.12, -1.57, 1.52, 0.0]
    #     time_from_start: 4.5
    #   - positions: [0.34, 0.0, 0.0, 0.21, 0.35, -0.2, 0.0, -1.57, 1.52, 0.0]
    #     time_from_start: 8.0
    #   - positions: [0.34, 0.0, 0.0, 0.21, 0.35, -3.0, 0.0, -1.57, 1.52, 0.0]
    #     time_from_start: 10.0
    #   - positions: [0.34, 0.0, 0.0, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
    #     time_from_start: 12.0
    #   meta:
    #     name: pregrasp1
    #     usage: demo
    #     description: 'pregrasp1'

    # tabletop_grasp1:
    #   joints: [torso_lift_joint, head_1_joint, head_2_joint, arm_1_joint,
    #   arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
    #   arm_6_joint, arm_7_joint]
    #   points:
    #   - positions: [0.34, -0.05, -0.63, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
    #     time_from_start: 2.0
    #   - positions: [0.34, -0.88, 0.07, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
    #     time_from_start: 4.0
    #   - positions: [0.34, -0.05, -0.63, 0.75, 0.23, -1.65, 1.15, -2.07, 0.20, -0.79]
    #     time_from_start: 8.5
    #   - positions: [0.34, -0.05, -0.63, 0.53, -0.18, -1.65, 1.52, -1.74, 0.20, -1.62]
    #     time_from_start: 10.5
    #   - positions: [0.34, -0.05, -0.63, 0.53, -0.40, -1.65, 1.52, -1.74, 0.20, -1.75]
    #     time_from_start: 12.5
    #   meta:
    #     name: tabletop_grasp1
    #     usage: demo
    #     description: 'tabletop_grasp1'


    # back_to_pregrasp1:
    #   joints: [torso_lift_joint, arm_1_joint,
    #   arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
    #   arm_6_joint, arm_7_joint]
    #   points:
    #   - positions: [0.34, 0.53, -0.40, -1.65, 1.52, -1.74, 0.20, -1.75]
    #     time_from_start: 2.0
    #   - positions: [0.34, 0.53, 0.12, -1.65, 1.52, -1.74, 0.20, -1.20]
    #     time_from_start: 4.0
    #   - positions: [0.34, 0.21, -0.2, -2.2, 1.15, -1.57, 0.2, 0.0]
    #     time_from_start: 6.0
    #   meta:
    #     name: back_to_pregrasp1
    #     usage: demo
    #     description: 'back_to_pregrasp1'


    # pickup_grasp1:
    #   joints: [torso_lift_joint, head_1_joint, head_2_joint, arm_1_joint,
    #   arm_2_joint, arm_3_joint, arm_4_joint, arm_5_joint,
    #   arm_6_joint, arm_7_joint]
    #   points:
    #   - positions: [0.34, -0.79, 0.09, 0.01, 0.35, -2.32, 1.13, -2.07, 0.87, -0.83]
    #     time_from_start: 6.5
    #   meta:
    #     name: pickup_grasp1
    #     usage: demo
    #     description: 'pickup_grasp1'

    nonono:
      joints: [arm_1_joint, arm_2_joint, arm_3_joint,
        arm_4_joint, arm_5_joint, arm_6_joint, arm_7_joint, hand_thumb_joint, hand_index_joint,
        hand_mrl_joint]
      meta: {description: nonono, name: nonono, usage: demo}
      points:
      - positions: [1.22, -0.901, -2.94, 1.962, 0.207, -0.031, 1.659,
          5.571, -0.001, 8.305]
        time_from_start: 0.0
      - positions: [1.22, -0.901, -3.119, 1.962, 0.125, 0.279, 1.659,
          5.571, -0.001, 8.306]
        time_from_start: 1.0
      - positions: [1.22, -0.902, -2.717, 1.962, 0.124, -0.279, 1.659,
          5.571, -0.001, 8.306]
        time_from_start: 2.0
      - positions: [1.22, -0.901, -3.119, 1.962, 0.125, 0.279, 1.659,
          5.571, -0.001, 8.306]
        time_from_start: 3.0
      - positions: [1.22, -0.902, -2.717, 1.962, 0.124, -0.279, 1.659,
          5.571, -0.001, 8.306]
        time_from_start: 4.0
      - positions: [1.22, -0.901, -2.819, 1.962, 0.166, 0.062, 1.577,
          0.0, -0.001, -0.001]
        time_from_start: 6.0

    self_presentation:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'hand_thumb_joint', 'hand_index_joint', 'hand_mrl_joint']
      points:
      - positions: [0.091, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0, -0.001, -0.0, -0.001]
        time_from_start: 0.0
      - positions: [0.197, 0.21, -1.02, -0.2, 2.12, -1.57, 1.52, 0.0, -0.001, -0.0, -0.001]
        time_from_start: 2.0
      - positions: [0.197, 0.195, 0.102, -0.972, 0.946, -1.57, 1.52, 0.0, -0.001, -0.0, -0.001]
        time_from_start: 5.5
      - positions: [0.197, 0.06, -0.63, 0.03, 0.16, -1.57, 0.682, -0.0, 4.963, -0.0, 8.658]
        time_from_start: 9.0
# pointing to base
      - positions: [0.197, 0.121, 0.157, 0.235, 1.611, -1.57, 0.682, -0.0, 4.947, -0.0, 8.662]
        time_from_start: 14.0
      - positions: [0.197, 0.121, 0.157, 0.235, 1.611, -1.57, 0.682, -0.0, 4.947, -0.0, 8.662]
        time_from_start: 16.0
#pointing to torso
      - positions: [0.197, 0.25, 0.37, 0.56, 2.01, -1.57, 0.993, -0.0, 4.947, -0.0, 8.658]
        time_from_start: 21.0
      - positions: [0.338, 0.25, 0.37, 0.559, 2.01, -1.57, 0.993, -0.0, 4.947, -0.0, 8.658]
        time_from_start: 28.0
      - positions: [0.338, 0.25, 0.37, 0.559, 2.01, -1.57, 0.993, -0.0, 4.947, -0.0, 8.658]
        time_from_start: 30.0
# pointing head
      - positions: [0.338, 0.17, -0.859, -2.64, 1.98, -1.825, 1.024, -0.332, 4.947, -0.0, 8.659]
        time_from_start: 35.0
      - positions: [0.338, 0.17, -0.859, -2.64, 1.98, -1.825, 1.024, -0.332, 4.947, -0.0, 8.659]
        time_from_start: 37.0
# pointing laptop tray
      - positions: [0.338, 0.17, -0.88, -3.25, 1.72, -1.245, 1.458, -0.33, 4.947, -0.0, 8.659]
        time_from_start: 39.0
      meta:
        name: self_presentation
        usage: demo
        description: 'self_presentation'



    follow_by_arm_initial_pose:
      joints: ['torso_lift_joint', 'arm_1_joint', 'arm_2_joint', 'arm_3_joint', 'arm_4_joint', 'arm_5_joint', 'arm_6_joint', 'arm_7_joint', 'hand_thumb_joint', 'hand_index_joint', 'hand_mrl_joint']
      points:
      - positions: [0.296, 1.61, -0.93, -3.14, 1.83, -1.577, -0.62, -1.577, -0.001, -0.0, -0.001]
        time_from_start: 0.0
      meta:
        name: follow_by_arm_initial_pose
        usage: demo
        description: 'follow_by_arm_initial_pose'
