# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2d_demo_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(320, 10, 471, 541))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 221, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 120, 113, 27))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 16, 17))
        self.label_3.setObjectName("label_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 160, 117, 22))
        self.radioButton_6.setObjectName("radioButton_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 16, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 90, 113, 27))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 180, 117, 22))
        self.radioButton_7.setObjectName("radioButton_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 210, 161, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 20, 161, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 50, 161, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 240, 161, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 290, 281, 361))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 40, 161, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 230, 117, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 120, 161, 27))
        self.pushButton.setObjectName("pushButton")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 180, 231, 22))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 70, 117, 22))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(25, 200, 41, 20))
        self.label_5.setObjectName("label_5")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(40, 90, 117, 22))
        self.radioButton_5.setObjectName("radioButton_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_5.setGeometry(QtCore.QRect(70, 200, 113, 27))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton.setGeometry(QtCore.QRect(40, 150, 231, 22))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2.raise_()
        self.pushButton_2.raise_()
        self.pushButton.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.label_5.raise_()
        self.lineEdit_5.raise_()
        self.radioButton.raise_()
        self.pushButton_2.raise_()
        self.radioButton_2.raise_()
        self.pushButton.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.label_5.raise_()
        self.lineEdit_5.raise_()
        self.radioButton.raise_()
        self.pushButton_2.raise_()
        self.radioButton_2.raise_()
        self.pushButton.raise_()
        self.radioButton_3.raise_()
        self.radioButton_4.raise_()
        self.label_5.raise_()
        self.radioButton_5.raise_()
        self.lineEdit_5.raise_()
        self.radioButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Plot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Learning from Demonstration"))
        self.lineEdit_3.setText(_translate("MainWindow", "-1"))
        self.label_3.setText(_translate("MainWindow", "y1"))
        self.radioButton_6.setText(_translate("MainWindow", "No obstacle"))
        self.label_4.setText(_translate("MainWindow", "y2"))
        self.lineEdit_4.setText(_translate("MainWindow", "1"))
        self.radioButton_7.setText(_translate("MainWindow", "Obstacle"))
        self.pushButton_3.setText(_translate("MainWindow", "Predict"))
        self.pushButton_5.setText(_translate("MainWindow", "Set context"))
        self.pushButton_4.setText(_translate("MainWindow", "Demonstrate"))
        self.pushButton_6.setText(_translate("MainWindow", "Enable keyboard"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Refinement"))
        self.pushButton_2.setText(_translate("MainWindow", "Refine"))
        self.radioButton_2.setText(_translate("MainWindow", "Normal"))
        self.pushButton.setText(_translate("MainWindow", "Add to model"))
        self.radioButton_3.setText(_translate("MainWindow", "Welford: forgetting factor"))
        self.radioButton_4.setText(_translate("MainWindow", "No obstacle"))
        self.label_5.setText(_translate("MainWindow", "alpha"))
        self.radioButton_5.setText(_translate("MainWindow", "Obstacle"))
        self.lineEdit_5.setText(_translate("MainWindow", "1"))
        self.radioButton.setText(_translate("MainWindow", "Welford: no forgetting factor"))

