# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2d_demo_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1198, 933)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(370, 10, 791, 781))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 10, 451, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 120, 113, 27))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 16, 17))
        self.label_3.setObjectName("label_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 160, 117, 22))
        self.radioButton_6.setObjectName("radioButton_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 16, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 90, 113, 27))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 180, 117, 22))
        self.radioButton_7.setObjectName("radioButton_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 210, 161, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_5.setGeometry(QtCore.QRect(0, 20, 161, 27))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 50, 161, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 240, 161, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_10.setGeometry(QtCore.QRect(170, 20, 161, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_11.setGeometry(QtCore.QRect(170, 50, 161, 27))
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 290, 361, 361))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 40, 161, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(20, 120, 161, 27))
        self.pushButton.setObjectName("pushButton")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 70, 117, 22))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_5.setGeometry(QtCore.QRect(40, 90, 117, 22))
        self.radioButton_5.setObjectName("radioButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 40, 161, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit.setGeometry(QtCore.QRect(190, 70, 161, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 120, 161, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 150, 231, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_2.setGeometry(QtCore.QRect(0, 100, 117, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton_3.setGeometry(QtCore.QRect(0, 50, 231, 22))
        self.radioButton_3.setObjectName("radioButton_3")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(0, 70, 41, 20))
        self.label_5.setObjectName("label_5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_5.setGeometry(QtCore.QRect(45, 70, 113, 27))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButton.setGeometry(QtCore.QRect(0, 20, 231, 22))
        self.radioButton.setObjectName("radioButton")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 10, 161, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_12 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_12.setGeometry(QtCore.QRect(20, 280, 161, 27))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.radioButton_4.raise_()
        self.radioButton_5.raise_()
        self.pushButton_7.raise_()
        self.lineEdit.raise_()
        self.pushButton_8.raise_()
        self.groupBox_4.raise_()
        self.pushButton_9.raise_()
        self.pushButton_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1198, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Plot"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Learning from Demonstration"))
        self.lineEdit_3.setText(_translate("MainWindow", "-1"))
        self.label_3.setText(_translate("MainWindow", "y1"))
        self.radioButton_6.setText(_translate("MainWindow", "No obstacle"))
        self.label_4.setText(_translate("MainWindow", "y2"))
        self.lineEdit_4.setText(_translate("MainWindow", "1"))
        self.radioButton_7.setText(_translate("MainWindow", "Obstacle"))
        self.pushButton_3.setText(_translate("MainWindow", "Predict"))
        self.pushButton_5.setText(_translate("MainWindow", "Set context"))
        self.pushButton_4.setText(_translate("MainWindow", "Demonstrate"))
        self.pushButton_6.setText(_translate("MainWindow", "Enable keyboard"))
        self.pushButton_10.setText(_translate("MainWindow", "Random context"))
        self.pushButton_11.setText(_translate("MainWindow", "Initialize model"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Refinement"))
        self.pushButton_2.setText(_translate("MainWindow", "Refine"))
        self.pushButton.setText(_translate("MainWindow", "Add to model"))
        self.radioButton_4.setText(_translate("MainWindow", "No obstacle"))
        self.radioButton_5.setText(_translate("MainWindow", "Obstacle"))
        self.pushButton_7.setText(_translate("MainWindow", "Load trajectory"))
        self.lineEdit.setText(_translate("MainWindow", "demonstration_1"))
        self.pushButton_8.setText(_translate("MainWindow", "Plot refinement"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Model adding method"))
        self.radioButton_2.setText(_translate("MainWindow", "Normal"))
        self.radioButton_3.setText(_translate("MainWindow", "Welford: forgetting factor"))
        self.label_5.setText(_translate("MainWindow", "alpha"))
        self.lineEdit_5.setText(_translate("MainWindow", "1"))
        self.radioButton.setText(_translate("MainWindow", "Welford: no forgetting factor"))
        self.pushButton_9.setText(_translate("MainWindow", "Clear plots"))
        self.pushButton_12.setText(_translate("MainWindow", "Done refining"))

