  dishwasher:
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50  

    upper_basket_controller:
      type: "position_controllers/JointPositionController"
      joint: upper_basket_joint
    lower_basket_controller:
      type: "position_controllers/JointPositionController"
      joint: lower_basket_joint
    door_controller:
      type: "position_controllers/JointPositionController"
      joint: door_joint