/gazebo_ros_control:   
  pid_gains:
    upper_basket_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    lower_basket_joint:
      p: 100.0
      i: 0.01 
      d: 10.0
    door_joint:
      p: 100.0
      i: 0.01 
      d: 10.0