controller_list:
  - name: fake_marco_arm_controller
    joints:
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: fake_marco_torso_controller
    joints:
      - torso_lift_joint
      - arm_1_joint
      - arm_2_joint
      - arm_3_joint
      - arm_4_joint
      - arm_5_joint
      - arm_6_joint
      - arm_7_joint
  - name: fake_gripper_controller
    joints:
      []
# initial:
#   - group: marco_arm
#     pose:  home