# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'offline_pendant.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1859, 1080)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 0, 1881, 641))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 650, 681, 371))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_10.setGeometry(QtCore.QRect(110, 30, 111, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 30, 41, 22))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_15.setGeometry(QtCore.QRect(10, 60, 117, 22))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_16.setGeometry(QtCore.QRect(10, 90, 117, 22))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_17.setGeometry(QtCore.QRect(60, 30, 117, 22))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_18.setGeometry(QtCore.QRect(60, 60, 117, 22))
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox_10)
        self.radioButton_19.setGeometry(QtCore.QRect(60, 90, 117, 22))
        self.radioButton_19.setObjectName("radioButton_19")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 30, 91, 81))
        self.groupBox_9.setObjectName("groupBox_9")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_11.setGeometry(QtCore.QRect(10, 30, 117, 22))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox_9)
        self.radioButton_12.setGeometry(QtCore.QRect(10, 60, 117, 22))
        self.radioButton_12.setObjectName("radioButton_12")
        self.groupBox_11 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_11.setGeometry(QtCore.QRect(240, 30, 241, 161))
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit.setGeometry(QtCore.QRect(0, 30, 41, 27))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton.setGeometry(QtCore.QRect(0, 60, 99, 27))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_11)
        self.groupBox_3.setGeometry(QtCore.QRect(110, 0, 120, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_21.setGeometry(QtCore.QRect(0, 30, 61, 27))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.pushButton_40 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_40.setGeometry(QtCore.QRect(0, 60, 90, 27))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_41.setGeometry(QtCore.QRect(0, 90, 90, 27))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_42.setGeometry(QtCore.QRect(440, 90, 90, 27))
        self.pushButton_42.setObjectName("pushButton_42")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(540, 30, 120, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_33 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_33.setGeometry(QtCore.QRect(0, 60, 101, 27))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_32 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_32.setGeometry(QtCore.QRect(0, 30, 91, 27))
        self.pushButton_32.setObjectName("pushButton_32")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 180, 271, 151))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton_29 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_29.setGeometry(QtCore.QRect(90, 20, 91, 27))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_31 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_31.setGeometry(QtCore.QRect(0, 20, 91, 27))
        self.pushButton_31.setObjectName("pushButton_31")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_20.setGeometry(QtCore.QRect(80, 60, 31, 27))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(0, 60, 91, 20))
        self.label_22.setObjectName("label_22")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 130, 97, 22))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox.setGeometry(QtCore.QRect(10, 100, 97, 22))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_30 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_30.setGeometry(QtCore.QRect(180, 20, 91, 27))
        self.pushButton_30.setObjectName("pushButton_30")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setGeometry(QtCore.QRect(350, 180, 271, 151))
        self.groupBox_8.setObjectName("groupBox_8")
        self.pushButton_34 = QtWidgets.QPushButton(self.groupBox_8)
        self.pushButton_34.setGeometry(QtCore.QRect(0, 20, 91, 27))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_8.setGeometry(QtCore.QRect(100, 0, 99, 27))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 150, 99, 27))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 150, 99, 27))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_11.setGeometry(QtCore.QRect(200, 0, 99, 27))
        self.pushButton_11.setObjectName("pushButton_11")
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(680, 660, 411, 171))
        self.groupBox_6.setObjectName("groupBox_6")
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 30, 150, 27))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_6.setGeometry(QtCore.QRect(170, 30, 150, 27))
        self.pushButton_6.setObjectName("pushButton_6")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton.setGeometry(QtCore.QRect(40, 60, 117, 22))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_6)
        self.radioButton_2.setGeometry(QtCore.QRect(40, 90, 117, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(680, 850, 411, 171))
        self.groupBox_7.setObjectName("groupBox_7")
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_24.setGeometry(QtCore.QRect(10, 30, 150, 27))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 30, 150, 27))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_5 = QtWidgets.QLabel(self.groupBox_7)
        self.label_5.setGeometry(QtCore.QRect(179, 67, 16, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_7)
        self.label_6.setGeometry(QtCore.QRect(179, 133, 16, 17))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setGeometry(QtCore.QRect(179, 100, 16, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_5.setGeometry(QtCore.QRect(200, 67, 91, 27))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_4.setGeometry(QtCore.QRect(200, 133, 91, 27))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_6.setGeometry(QtCore.QRect(200, 100, 91, 27))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_7.setGeometry(QtCore.QRect(110, 100, 97, 22))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 130, 97, 22))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 100, 97, 22))
        self.checkBox_3.setObjectName("checkBox_3")
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 70, 150, 27))
        self.pushButton_22.setObjectName("pushButton_22")
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(1060, 650, 511, 361))
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_17 = QtWidgets.QLabel(self.groupBox_12)
        self.label_17.setGeometry(QtCore.QRect(40, 30, 31, 17))
        self.label_17.setObjectName("label_17")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 50, 90, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 80, 88, 27))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_39 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_39.setGeometry(QtCore.QRect(10, 150, 90, 27))
        self.pushButton_39.setObjectName("pushButton_39")
        self.label_25 = QtWidgets.QLabel(self.groupBox_12)
        self.label_25.setGeometry(QtCore.QRect(10, 130, 91, 17))
        self.label_25.setObjectName("label_25")
        self.pushButton_38 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_38.setGeometry(QtCore.QRect(10, 180, 88, 27))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_43 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_43.setGeometry(QtCore.QRect(120, 150, 90, 27))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_44.setGeometry(QtCore.QRect(120, 180, 88, 27))
        self.pushButton_44.setObjectName("pushButton_44")
        self.label_26 = QtWidgets.QLabel(self.groupBox_12)
        self.label_26.setGeometry(QtCore.QRect(120, 130, 91, 17))
        self.label_26.setObjectName("label_26")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1859, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_4.setTitle(_translate("MainWindow", "RViz"))
        self.groupBox.setTitle(_translate("MainWindow", "Experiment"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Object position"))
        self.radioButton_14.setText(_translate("MainWindow", "&1"))
        self.radioButton_15.setText(_translate("MainWindow", "&2"))
        self.radioButton_16.setText(_translate("MainWindow", "&3"))
        self.radioButton_17.setText(_translate("MainWindow", "&4"))
        self.radioButton_18.setText(_translate("MainWindow", "&5"))
        self.radioButton_19.setText(_translate("MainWindow", "&6"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Variation"))
        self.radioButton_11.setText(_translate("MainWindow", "1"))
        self.radioButton_12.setText(_translate("MainWindow", "2"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Trial"))
        self.pushButton.setText(_translate("MainWindow", "Next"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Timer"))
        self.lineEdit_21.setText(_translate("MainWindow", "0"))
        self.pushButton_40.setText(_translate("MainWindow", "Start"))
        self.pushButton_41.setText(_translate("MainWindow", "Stop"))
        self.pushButton_42.setText(_translate("MainWindow", "Zero"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Failure"))
        self.pushButton_33.setText(_translate("MainWindow", "Object missed"))
        self.pushButton_32.setText(_translate("MainWindow", "Obstacle hit"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Data"))
        self.pushButton_29.setText(_translate("MainWindow", "Load"))
        self.pushButton_31.setText(_translate("MainWindow", "Store"))
        self.lineEdit_20.setText(_translate("MainWindow", "1"))
        self.label_22.setText(_translate("MainWindow", "Participant"))
        self.checkBox_2.setText(_translate("MainWindow", "Predicted"))
        self.checkBox.setText(_translate("MainWindow", "Refined"))
        self.pushButton_30.setText(_translate("MainWindow", "Save"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Movement"))
        self.pushButton_34.setText(_translate("MainWindow", "Initial pose"))
        self.pushButton_8.setText(_translate("MainWindow", "Initialize"))
        self.pushButton_9.setText(_translate("MainWindow", "Set"))
        self.pushButton_10.setText(_translate("MainWindow", "Set"))
        self.pushButton_11.setText(_translate("MainWindow", "Exit"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Refinement"))
        self.pushButton_21.setText(_translate("MainWindow", "Refine"))
        self.pushButton_6.setText(_translate("MainWindow", "Add to model"))
        self.radioButton.setText(_translate("MainWindow", "Predi&ction"))
        self.radioButton_2.setText(_translate("MainWindow", "Refi&nement"))
        self.groupBox_7.setTitle(_translate("MainWindow", "LfD"))
        self.pushButton_24.setText(_translate("MainWindow", "Predict"))
        self.pushButton_7.setText(_translate("MainWindow", "Get context"))
        self.label_5.setText(_translate("MainWindow", "x: "))
        self.label_6.setText(_translate("MainWindow", "z: "))
        self.label_4.setText(_translate("MainWindow", "y: "))
        self.checkBox_7.setText(_translate("MainWindow", "Clear"))
        self.checkBox_4.setText(_translate("MainWindow", "Predicted"))
        self.checkBox_3.setText(_translate("MainWindow", "Refined"))
        self.pushButton_22.setText(_translate("MainWindow", "Visualize"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Nodes"))
        self.label_17.setText(_translate("MainWindow", "LfD"))
        self.pushButton_3.setText(_translate("MainWindow", "Start"))
        self.pushButton_4.setText(_translate("MainWindow", "Stop"))
        self.pushButton_39.setText(_translate("MainWindow", "Start"))
        self.label_25.setText(_translate("MainWindow", "Keyboard"))
        self.pushButton_38.setText(_translate("MainWindow", "Stop"))
        self.pushButton_43.setText(_translate("MainWindow", "Start"))
        self.pushButton_44.setText(_translate("MainWindow", "Stop"))
        self.label_26.setText(_translate("MainWindow", "Logger"))

