gripper_controller:
  type: "position_controllers/JointTrajectoryController"
  # check_mode: True
  joints: 
    - gripper_joint
  # actuators:
  #   - gripper_motor
  constraints:
    goal_time: &goal_time_constraint 0.6
    stopped_velocity_tolerance: &stopped_velocity_constraint 0.05
    gripper_joint:
      goal: &goal_pos_constraint 0.02

  stop_trajectory_duration: 0.0

    #   type: effort_controllers/JointPositionController
    #   pid: {p: 100.0, i: 0.01, d: 10.0}
    #   actuators:
    # - gripper_motor
